/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "../../../Include/Port.hpp"

#include "stm32h7xx.h"  // Include the STM32 device-specific header file

void FPU_init(void)
{
    // Set CP10 and CP11 Full Access
    SCB->CPACR |= ((3UL << 20) | (3UL << 22));
}


int main(void)
{
	FPU_init();

	CppRtos::Port::Port port;
    /* Loop forever */
	for(;;);
}
