/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "Port.hpp"
#include "Task.hpp"
#include "Kernel.hpp"

#include "stm32h7xx.h"  // Include the STM32 device-specific header file

#include <type_traits>

void FPU_init(void)
{
    // Set CP10 and CP11 Full Access
    SCB->CPACR |= ((3UL << 20) | (3UL << 22));
}


class Task1 : public CppRtos::Task<2048>
{
public:

	Task1():CppRtos::Task<2048>()
	{

	}

	void run() override
	{
		while(true)
		{
		}
	}
};


std::aligned_storage_t<sizeof(CppRtos::Kernel)> _prealoc_kernel_mem;

int main(void)
{
	FPU_init();

	CppRtos::KernelFactory& kernelFactory  = CppRtos::KernelFactory::getInstance();
	CppRtos::Kernel* ptrKernel = kernelFactory.create( &_prealoc_kernel_mem );


	std::string_view taskName1 = "Task 1";

	Task1 task1;
	task1.setPriority(50);
	task1.setName( taskName1);

	ptrKernel->addTask(task1);




	//CppRtos::Port::Port port;
    /* Loop forever */
	for(;;);
}
