/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <new>
#include <cstring>
#include "Port.hpp"
#include "Task.hpp"
#include "Kernel.hpp"
#include "Mutex.hpp"
#include <memory>

#include "stm32h7xx_hal.h"
#include "stm32h7xx_hal_pwr_ex.h"

//#include "stm32h7xx_hal_cortex.h"
#include <type_traits>

void FPU_init(void)
{
    // Set CP10 and CP11 Full Access
    SCB->CPACR |= ((3UL << 20) | (3UL << 22));
}

class Task1 : public CppRtos::Task<2048>
{
public:

	Task1():CppRtos::Task<2048>()
	{

	}

  CppRtos::Mutex* mutex;

	void run() override
	{
		while(true)
		{
      int a = 0;
        //mutex->acquire(1000);
        for ( int i = 0 ; i < 1000000; i++ )
        {
          a++;
        }
        //mutex->release();
		}
	}
};



class Task2 : public CppRtos::Task<4096>
{
public:

	Task2():CppRtos::Task<4096>()
	{

	}

  CppRtos::Mutex* mutex;
  
	void run() override
	{
    int a = 0;
		while(true)
		{
      //mutex->acquire(1000);
      for ( int i = 0 ; i < 1000000; i++ )
      {
        a++;
      }
      //mutex->release();
		}
	}
};

static std::aligned_storage_t<sizeof(CppRtos::Kernel)> _prealoc_kernel_mem;
static std::aligned_storage_t<sizeof(Task1)> _prealoc_task1;
static std::aligned_storage_t<sizeof(Task2)> _prealoc_task2;
static std::aligned_storage_t<sizeof(CppRtos::Mutex)> _prealoc_mutex1;


void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}

void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Supply configuration update enable
  */
  HAL_PWREx_ConfigSupply(PWR_LDO_SUPPLY);

  /** Configure the main internal regulator output voltage
  */
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE2);

  while(!__HAL_PWR_GET_FLAG(PWR_FLAG_VOSRDY)) {}

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI|RCC_OSCILLATORTYPE_LSI
                              |RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_BYPASS;
  RCC_OscInitStruct.HSIState = RCC_HSI_DIV1;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.LSIState = RCC_LSI_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = 22;
  RCC_OscInitStruct.PLL.PLLN = 169;
  RCC_OscInitStruct.PLL.PLLP = 2;
  RCC_OscInitStruct.PLL.PLLQ = 4;
  RCC_OscInitStruct.PLL.PLLR = 2;
  RCC_OscInitStruct.PLL.PLLRGE = RCC_PLL1VCIRANGE_0;
  RCC_OscInitStruct.PLL.PLLVCOSEL = RCC_PLL1VCOWIDE;
  RCC_OscInitStruct.PLL.PLLFRACN = 0;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2
                              |RCC_CLOCKTYPE_D3PCLK1|RCC_CLOCKTYPE_D1PCLK1;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;
  RCC_ClkInitStruct.SYSCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB3CLKDivider = RCC_APB3_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_APB1_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_APB2_DIV1;
  RCC_ClkInitStruct.APB4CLKDivider = RCC_APB4_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_1) != HAL_OK)
  {
    Error_Handler();
  }
}

int main(void)
{

int a = 0;
a++;
	SCB_EnableICache();
	HAL_Init();

	SystemClock_Config();

	FPU_init();


	CppRtos::KernelFactory& kernelFactory  = CppRtos::KernelFactory::getInstance();
	CppRtos::Kernel* ptrKernel = kernelFactory.create( &_prealoc_kernel_mem );

  std::memset(&_prealoc_task1, 0xDE, sizeof(Task1));
  std::memset(&_prealoc_task2, 0xDE, sizeof(Task2));
 
  CppRtos::Mutex* mutex = new(&_prealoc_mutex1) CppRtos::Mutex;
  Task1* task1 = new(&_prealoc_task1) Task1;
  Task2* task2 = new(&_prealoc_task2) Task2;


 
  task1->mutex = mutex;
  task2->mutex = mutex;


  std::string_view taskName1 = "Task 1";
	task1->setPriority( CppRtos::TaskPriority::PRIORITY_LOW );
	task1->setName( taskName1);
  ptrKernel->addTask(*task1);

  std::string_view taskName2 = "Task 2";
	task2->setPriority( CppRtos::TaskPriority::PRIORITY_LOW );
	task2->setName( taskName2);
 	ptrKernel->addTask(*task2);

	ptrKernel->start();



	//CppRtos::Port::Port port;


	for(;;);
}
