/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <new>
#include <cstring>
#include "Port.hpp"
#include "Task.hpp"
#include "KernelFactory.hpp"
#include "Kernel.hpp"
#include "Timer.hpp"
#include "Mutex.hpp"
#include "Semaphore.hpp"
#include <memory>

#include "MessageQueue.hpp"

#include "stm32h7xx_hal.h"
#include "stm32h7xx_hal_pwr_ex.h"

//#include "stm32h7xx_hal_cortex.h"
#include <type_traits>

void FPU_init(void)
{
    // Set CP10 and CP11 Full Access
    SCB->CPACR |= ((3UL << 20) | (3UL << 22));
}

void timerCallback1(void* test)
{
}

void timerCallback2(void* test)
{
}
	
    extern "C" void hard_fault_handler_c(unsigned int * hardfault_args)
    {
      unsigned int stacked_r0 = ((unsigned long) hardfault_args[0]);
      unsigned int stacked_r1 = ((unsigned long) hardfault_args[1]);
      unsigned int stacked_r2 = ((unsigned long) hardfault_args[2]);
      unsigned int stacked_r3 = ((unsigned long) hardfault_args[3]);
      unsigned int stacked_r12 = ((unsigned long) hardfault_args[4]);
      unsigned int stacked_lr = ((unsigned long) hardfault_args[5]);
      unsigned int stacked_pc = ((unsigned long) hardfault_args[6]);
      unsigned int stacked_psr = ((unsigned long) hardfault_args[7]);

      // Fault Status Register (CFSR)
      //Subregisters            
        // MMFSR (Memory Management Fault Status Register)
        //     Bit 0: IACCVIOL: Instruction access violation.
        //     Bit 1: DACCVIOL: Data access violation.
        //     Bit 3: MUNSTKERR: Unstacking error.
        //     Bit 4: MSTKERR: Stacking error.
        //     Bit 5: MLSPERR: Lazy state preservation error.
        //     Bit 7: MMARVALID: Indicates MMFAR is valid.

        // BFSR (Bus Fault Status Register)
        //     Bit 8: IBUSERR: Instruction bus error.
        //     Bit 9: PRECISERR: Precise data bus error.
        //     Bit 10: IMPRECISERR: Imprecise data bus error.
        //     Bit 11: UNSTKERR: Unstacking error.
        //     Bit 12: STKERR: Stacking error.
        //     Bit 13: LSPERR: Lazy state preservation error.
        //     Bit 15: BFARVALID: Indicates BFAR is valid.

        // UFSR (Usage Fault Status Register)
        //     Bit 16: UNDEFINSTR: Undefined instruction.
        //     Bit 17: INVSTATE: Invalid state.
        //     Bit 18: INVPC: Invalid PC load usage fault.
        //     Bit 19: NOCP: No coprocessor.
        //     Bits 24-25: UNALIGNED: Unaligned access usage fault.
        //     Bits 26-27: DIVBYZERO: Divide by zero.
      uint32_t cfsr = SCB->CFSR;

      //HardFault Status Register (HFSR)
        //  Bits:
        //  0: Reserved.
        //  1: Indicates a forced hard fault.
        //  30: Debug event.
        //  31: Indicates vector table read fault.        
      uint32_t hfsr = SCB->HFSR;

      //Debug Fault Status Register(DFSR)
      uint32_t dfsr = SCB->DFSR;

      //Auxiliary Fault Status Register (AFSR)
      uint32_t afsr = SCB->AFSR;

      //MemManage Fault Address Register (MMFAR)
      uint32_t mmfar = SCB->MMFAR;

      //Bus Fault Address Register (BFAR)
      uint32_t bfar = SCB->BFAR;

		while (1);  // Infinite loop to catch HardFault
    assert( cfsr != 0u );
    assert( hfsr != 0u );
    assert( dfsr != 0u );
    assert( afsr != 0u );
    assert( mmfar != 0u );
    assert( bfar != 0u );
    assert( stacked_r0 != 0u );
    assert( stacked_r1 != 0u );
    assert( stacked_r2 != 0u );
    assert( stacked_r3 != 0u );
    assert( stacked_r12 != 0u );
    assert( stacked_lr != 0u );
    assert( stacked_pc != 0u );
    assert( stacked_psr != 0u );
	}

  extern "C" void HardFault_Handler(void)
	{
    asm volatile (
        "TST lr, #4         \n"
        "ITE EQ             \n"
        "MRSEQ r0, MSP      \n"
        "MRSNE r0, PSP      \n"
        "B hard_fault_handler_c \n"
    );
  }

	extern "C" void MemManage_Handler(void)
	{
		while (1);  // Infinite loop to catch Memory Management Fault
	}

	extern "C" void BusFault_Handler(void)
	{
		while (1);  // Infinite loop to catch Bus Fault
	}

	extern "C" void UsageFault_Handler(void)
	{
		while (1);  // Infinite loop to catch Usage Fault
	}

static std::aligned_storage_t<2048,4> _stack_task1;
static std::aligned_storage_t<2048,4> _stack_task2;
static std::aligned_storage_t<2048,4> _stack_task3;

CppRtos::Semaphore* semaphore1;


struct TestMsg
{
	int id;
	char text[99];
	/* data */
};


CppRtos::MessageQueue<TestMsg, 30> msgQueue1;


class Task1 : public CppRtos::Task
{
public:

	Task1():CppRtos::Task(_stack_task1.__data, 2048)
	{

	}

    CppRtos::Mutex* mutex;
    CppRtos::MessageQueue<TestMsg, 30> *ptrMsgQueue;

	void run() override
	{
     int a = 0;
		while(true)
		{
      auto result = mutex->acquire(1000);
      if (result == CppRtos::MutexResult::Success)
      {
        for ( int i = 0 ; i < 10000; i++ )
        {
          a++;
        }
        a = 0;
        mutex->release();
      }
      else
      {
        a = 0;
      }
		}
	}
};



class Task2 : public CppRtos::Task
{
public:

	Task2():CppRtos::Task( _stack_task2.__data, 2048 )
	{

	}

	CppRtos::MessageQueue<TestMsg, 30> *ptrMsgQueue;

    CppRtos::Mutex* mutex;
  
	void run() override
	{
    int a = 0;
		while(true)
		{
      auto result = mutex->acquire(1000);
      if (result == CppRtos::MutexResult::Success)
      {
        for ( int i = 0 ; i < 10000; i++ )
        {
          a++;
        }
        a = 0;
        mutex->release();
        this->sleep(5000);
      	TestMsg msg{};
      	msg.id = 1;

      	ptrMsgQueue->send(msg,1000);
        semaphore1->flush();
      }
      else
      {
        a = 0;
      }
		}
	}
};

class Task3 : public CppRtos::Task
{
public:

	Task3():CppRtos::Task(_stack_task3.__data, 2048)
	{
	}

  CppRtos::Mutex* mutex;

	void run() override
	{
     int a = 0;
		while(true)
		{
      auto result = semaphore1->wait(13000);
      if (result == CppRtos::SemResult::Success)
      {
        for ( int i = 0 ; i < 10000; i++ )
        {
          a++;
        }
        a = 0;
      }
      else
      {
        a = 0;
      }
		}
	}
};


static std::aligned_storage_t<sizeof(CppRtos::Kernel),4> _prealoc_kernel_mem;
static std::aligned_storage_t<sizeof(Task1),4> _prealoc_task1;
static std::aligned_storage_t<sizeof(Task2),4> _prealoc_task2;
static std::aligned_storage_t<sizeof(Task2),4> _prealoc_task3;


static std::aligned_storage_t<1024,4> _prealoc_barier;
static std::aligned_storage_t<sizeof(CppRtos::Mutex),4> _prealoc_mutex1;
static std::aligned_storage_t<sizeof(CppRtos::Timer),4> _prealoc_timer1;
static std::aligned_storage_t<sizeof(CppRtos::Timer),4> _prealoc_timer2;
static std::aligned_storage_t<sizeof(CppRtos::Semaphore),4> _prealoc_semaphore1;


void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}

void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Supply configuration update enable
  */
  HAL_PWREx_ConfigSupply(PWR_LDO_SUPPLY);

  /** Configure the main internal regulator output voltage
  */
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE2);

  while(!__HAL_PWR_GET_FLAG(PWR_FLAG_VOSRDY)) {}

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI|RCC_OSCILLATORTYPE_LSI
                              |RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_BYPASS;
  RCC_OscInitStruct.HSIState = RCC_HSI_DIV1;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.LSIState = RCC_LSI_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = 22;
  RCC_OscInitStruct.PLL.PLLN = 169;
  RCC_OscInitStruct.PLL.PLLP = 2;
  RCC_OscInitStruct.PLL.PLLQ = 4;
  RCC_OscInitStruct.PLL.PLLR = 2;
  RCC_OscInitStruct.PLL.PLLRGE = RCC_PLL1VCIRANGE_0;
  RCC_OscInitStruct.PLL.PLLVCOSEL = RCC_PLL1VCOWIDE;
  RCC_OscInitStruct.PLL.PLLFRACN = 0;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2
                              |RCC_CLOCKTYPE_D3PCLK1|RCC_CLOCKTYPE_D1PCLK1;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;
  RCC_ClkInitStruct.SYSCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB3CLKDivider = RCC_APB3_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_APB1_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_APB2_DIV1;
  RCC_ClkInitStruct.APB4CLKDivider = RCC_APB4_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_1) != HAL_OK)
  {
    Error_Handler();
  }
}

int main(void)
{

    int a = 0;
    a++;
    SCB_EnableICache();
    HAL_Init();

    SystemClock_Config();

    FPU_init();


    CppRtos::KernelFactory& kernelFactory  = CppRtos::KernelFactory::getInstance();
    CppRtos::Kernel* ptrKernel = kernelFactory.create( &_prealoc_kernel_mem );

    std::memset(&_prealoc_task1, 0xDE, sizeof(Task1));
    std::memset(&_prealoc_barier, 0xDE, 1024);


    CppRtos::Mutex* mutex = new(&_prealoc_mutex1) CppRtos::Mutex;
    
    semaphore1 = new(&_prealoc_semaphore1)  CppRtos::Semaphore(1,0);

    Task1* task1 = new(&_prealoc_task1) Task1();
    Task2* task2 = new(&_prealoc_task2) Task2();
    Task3* task3 = new(&_prealoc_task3) Task3();

    

    task1->mutex = mutex;
	task1->ptrMsgQueue = &msgQueue1;
    task2->mutex = mutex;
	task2->ptrMsgQueue = &msgQueue1;


    std::string_view taskName1 = "Task 1";
    task1->setPriority( CppRtos::TaskPriority::PRIORITY_LOW );
    task1->setName( taskName1);
    ptrKernel->addTask(*task1);

    std::string_view taskName2 = "Task 2";
    task2->setPriority( CppRtos::TaskPriority::PRIORITY_LOW );
    task2->setName( taskName2);
    ptrKernel->addTask(*task2);

    std::string_view taskName3 = "Task 3";
    task3->setPriority( CppRtos::TaskPriority::PRIORITY_MODERATELY_LOW );
    task3->setName( taskName3);
    ptrKernel->addTask(*task3);

    CppRtos::Timer* timer1 = new(&_prealoc_timer1) CppRtos::Timer(timerCallback1, 3000, true, nullptr);
    CppRtos::Timer* timer2 = new(&_prealoc_timer2) CppRtos::Timer(timerCallback2, 3000, true, nullptr);
 
    if (ptrKernel->addTimer(timer1))
    {
      timer1->start();
    }

    if (ptrKernel->addTimer(timer2))
    {
      timer2->start();
    }

    ptrKernel->start();



    //CppRtos::Port::Port port;


    for(;;);
}
